### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by TwistedModding** [Qudix/QUI-SKSE#1]
Heya, im just putting a list of nice to have features that you can possibly implement in the future.

Search bar

Scrolling with the scroll wheel

Save position in the list after searching through a specific esp

**Comment by qudix** [comment]
>Search bar

A definite possibility.

>Scrolling with the scroll wheel

This already exists.

>Save position in the list after searching through a specific esp

The plugin list already saves it's position. The only exception is the form type list, due to current limitations.

**Comment by iEx5** [comment]
> Add log feature (default false) to log if plugin initialized properly.

> Add VR Support (I can test it if you need someone with headset) [Discord: iEx#8670]
For now SKSEVR says:
plugin H:\SteamLow\steamapps\common\SkyrimVR\Data\SKSE\Plugins\\QUI.dll does not appear to be an SKSE plugin.

> Add description which says it's Additemmenu alternative for Skyrim SE/AE/(VR?), so people who is trying to find a solution for current additemmenu could find your github page. (At least i tried to search it like that :])

**Comment by qudix** [comment]
1. It already has a log file...? `My Documents/My Games/Skyrim Special Edition/SKSE/QUI.log`

2. For VR, I don't have a headset so I'm not comfortable stumbling around trying to get something to work for that platform. Sorry.

3. I'm not fully advertising this project just yet. Eventually this will be uploaded to the Nexus once I'm somewhat satisfied with the feature set and no serious bugs are found.

**Comment by name1esshero** [comment]
any chance you could add controller support? I use a laptop without a scroll wheel and I normally play with my xbox one controller because it's familiar and easy.

**Comment by RaulMZE** [comment]
First of all, thanks for the mod!

1. Please make the menu window a little larger, I have bad sight


2. Add a "configuration settings" file in the SKSE folder like other mods to tweak the mod, like to modify the quantity of items shown.
                                                              OR
2. Or make it possible to choose a exact quantity of the items you will take, like 2 out 5 swords, instead of take all (5).

**Comment by qudix** [comment]
1. Not sure how much larger I could make the interface without interfering with other elements.
2. It already had/has a config file...? `SKSE/Plugins/QUI.toml`
3. Already there.
