### ISSUE TITLE
A dll plugin failed

### ISSUE THREAD

**Issue by tacio98** [Qudix/QUI-SKSE#10]
I played with QUI and it worked before, but I need to reinstall the game and when QUI started to appear a warning before the game opens:

"A dll plugin failed to load properly. If a new version of Skyrim has just been released, it probably needs to be updated. Please contact the plugin author for more information.

QUI.dll failed to load plugin (000007E)

Continuing to load may result in loss of saved data or other inappropriate behavior.

So I enter the game, press F11 and the CHI - SKSE doesn't work, nothing happens.

![skse foto](https://user-images.githubusercontent.com/95988369/145696235-18180f5c-bd31-4342-86e0-07a58abfc360.PNG)

**Comment by qudix** [comment]
What's the version of the game *and* SKSE

**Comment by tacio98** [comment]
Preliminary AE build 2.1.3 (skyrim version1.6.323)

about four days ago I used your mod and it worked. I tuned the game today, when I went to install your mod it shows this notification, it only appears when I put your mod files. If I take it off, this notification no longer appears. I saw some comments saying that when they pressed F11 nothing happened, maybe anticipating having the same problem.

**Comment by qudix** [comment]
Can't be a problem on my end. If it loaded once it will always load unless something else on your end changed. The only other dependency it needs besides SKSE64 is Address Library. It may also error if you are missing crucial files, like the interfaces (swf) or the config QUI.toml

**Comment by tacio98** [comment]
I have the address library, i just get this message "a plugin dll failed" when i place its files. If I delete the files this message doesn't appear.

Here's a picture of how the files are allocated in case you want to spot something wrong.
![data skse plugin](https://user-images.githubusercontent.com/95988369/145723349-d0da09aa-50c6-4137-9fda-56fd89a9f938.PNG)
![interface folder](https://user-images.githubusercontent.com/95988369/145723351-6816d915-3dff-4aa4-b13e-7b5c3bd121b6.PNG)

**Comment by tacio98** [comment]
![qui folder](https://user-images.githubusercontent.com/95988369/145723636-a1e100b3-605a-464b-8dfb-a2ba8c056d31.PNG)
![qui 2](https://user-images.githubusercontent.com/95988369/145723641-21cbb7f9-dfb6-4016-ad11-8189e585d9cb.PNG)

**Comment by qudix** [comment]
Closing for now, if you still need help you may reopen this issue.
