### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by Davinaa23** [Qudix/QUI-SKSE#11]
Hello, when i press F11 the game just stops working and get this error                                                            
           
PluginExplorerMenu.cpp(38): [critical] PluginExplorerMenu did not have a view due to missing dependencies!

**Comment by JRTek7** [comment]
I'm getting the same issue under the latest Skyrim AE update (1.6.342). Made sure SKSE and Address Library were updated to AE versions 1.6.x as well.

![Qui Error](https://user-images.githubusercontent.com/96208666/146271215-fb2c8266-09ae-438d-9b56-cc89066d0278.png)

**Comment by JRTek7** [comment]
@Davinaa23, if you don't have SkyUI installed, try installing and see if it resolves this error. Installing SkyUI seem to resolve this QUI.dll error for me and got QUI working.

**Comment by qudix** [comment]
Huh, that would actually make sense because I use SkyUI's button prompts...

**Comment by JRTek7** [comment]
Indeed. It may not be a bad idea to also make SkyUI a requirement as well. Exceptional work on this by the way!! Works just as good if not better than additemmenu.
