### ISSUE TITLE
plugin does not load

### ISSUE THREAD

**Issue by meninodacam** [Qudix/QUI-SKSE#13]
Versions QUI - AE 0.2.1 and not 2.2 are working for me. My Skyrim is at version 1.6.323.08 and SKSE 2.1.3.

Now when I start Skyrim I get this warning and F11 doesn't open the menu,
![skse foto](https://user-images.githubusercontent.com/96266001/146459512-31bf0f01-ae57-45e1-a1ee-b5a3d8a800b0.PNG)

**Comment by plankton11** [comment]
https://github.com/Qudix/QUI-SKSE/releases/tag/v0.2.1

**Comment by meninodacam** [comment]
> https://github.com/Qudix/QUI-SKSE/releases/tag/v0.2.1

is this a fix?

**Comment by qudix** [comment]
Closing as no further info has been provided.
