### ISSUE TITLE
Mod won’t start

### ISSUE THREAD

**Issue by sarahanntalley** [Qudix/QUI-SKSE#14]
I have all the requirements and have put the mod in the data folder in SSE and nothing happens when I press F11

**Comment by tensei123** [comment]
Same here. Mod installed with NM, dependense are installed.
I can't see the log on SKSE folder.
Using AE version.

**Comment by dfmarulanda** [comment]
Did you make it work?

**Comment by AeliusRuivus** [comment]
I was having this issue, took me a while to figure that F11 wasn't working on my PC for some reason. The mod mentions that you can change the bound key, but I didn't see any mention on what are the codes. After some trial and error, this table looks like it could be it: http://wiki.tesnexus.com/index.php/DirectX_Scancodes_And_How_To_Use_Them

**Comment by qudix** [comment]
Closing as no further info has been provided. If you are still having problems feel free to re-open or create a new issue.

**Comment by sibouazza13** [comment]
same problem, please tell me how to fix it if u know how
