### ISSUE TITLE
CTD on f11 use

### ISSUE THREAD

**Issue by Raggtop666** [Qudix/QUI-SKSE#15]
so i have tried you QUI-SKSE main and i cant get the F11 to work and as i was reading i saw the QUI AE build and as i used the F11 it CTD im using Vortex as my mod manger and i have all the Required mods installed is there somthing that i missed in the install if not then I'd say its a big bug my attempt was new game using ASLAL mod and using QAsmoke for testing and both CTD

**Comment by rrgraw** [comment]
I think that is caused by using SSE Engine Fixes (SKSE64 plugin) at the some time as this mod.

**Comment by MBassoX** [comment]
i have similar issue.. sometimes it works and suddenly i press f11 it ctd. it nedd to be updated

**Comment by tensei123** [comment]
Same here, not working, CTD not happen to me just never open the mod.

**Comment by qudix** [comment]
Closing as there is not enough info, like crash logs or crash dumps (etc).
