### ISSUE TITLE
Incorrect MoreHUD Inventory Edition path

### ISSUE THREAD

**Issue by derickso** [Qudix/QUI-SKSE#18]
QUI.log:

`Logger.h(22): [info] Main Menu: Error, BSScaleformFileOpener failed to open Interface/moreHUDIE/config.txt`

moreHUD IE store its config file in Interface/**exported**/moreHUDIE/config.txt

**Comment by qudix** [comment]
Not related to my mod, it's just attaching a logger to the main menu swf which prints things previously gone unnoticed.
