### ISSUE TITLE
Steal tag on all items

### ISSUE THREAD

**Issue by Kepler-16b** [Qudix/QUI-SKSE#19]
Issue: All items has steal tag on them, taking them will be considered crime and bounty added.
To reproduce: Open QUI in any inn.

**Comment by qudix** [comment]
Once I have some free time, I'll get to fixing this. It's a rather high priority.

**Comment by qudix** [comment]
I have a fix for this that'll be in the next update

**Comment by qudix** [comment]
This should now be fixed in the v0.2.3 release.
