### ISSUE TITLE
CTD when trying to open this

### ISSUE THREAD

**Issue by zhongjiedong** [Qudix/QUI-SKSE#2]
I had a spell out on right hand and shield on left. Attempting to open it caused a ctd. Crashlog attache
[Crash_2021_10_30_22-47-4.txt](https://github.com/Qudix/QUI-SKSE/files/7447650/Crash_2021_10_30_22-47-4.txt)
d

**Comment by qudix** [comment]
Is the crash reproducible? Because I can't replicate the issue.

**Comment by zhongjiedong** [comment]
Yes every time i press f11 it just crashes. Not sure how it worked the one time 🤔

**Comment by TwistedModding** [comment]
I'm unable to replicate either.

**Comment by zhongjiedong** [comment]
I wonder if it's because of the Dienes Tools https://www.nexusmods.com/skyrimspecialedition/mods/31187

**Comment by Stas-sudo** [comment]
@zhongjiedong i don't use the mod you mentioned, but i'm getting the CTD's too.

**Comment by qudix** [comment]
This should be fixed in the latest 0.2.2 release.
