### ISSUE TITLE
Crashes when saving and loading FIXED IT WAS MY FAULT

### ISSUE THREAD

**Issue by agnariF** [Qudix/QUI-SKSE#20]
It crashes when loading and saving, even after disabling and uninstalling, EDIT: I fixed it by reinstalling and uninstalling a similar mod that didnt work.

**Comment by DoofyAss** [comment]
Are you sure?

**Comment by agnariF** [comment]
I fixed it, idk how but I reinstalled and it worked again, sorry i forgot to comment this
