### ISSUE TITLE
Qui 2.2 works good

### ISSUE THREAD

**Issue by Lat3rn** [Qudix/QUI-SKSE#22]
There's some issues I'm having
1- when i open a mod throw qui like an armor mod so it's pop up and showing
Mythril armor helmet 5
             Chest armor 5
  When press get item 1 time sometimes it only pick 1 item but sometimes it will add all 5 of them at once even you click 1 time!

2- when i open big mod like arcanum or magic apocalypse ctd
Otherwise nopre issues, you did a great job.

**Comment by qudix** [comment]
1. That's a Vanilla/SkyUI thing/feature, not related to my mod.
2. I would need further info for this, such as a crash log or crash dump.
