### ISSUE TITLE
Unknown value for changing menu key

### ISSUE THREAD

**Issue by Billyone1739** [Qudix/QUI-SKSE#26]
How are you finding your numerical value for the f11 key?

I need to change it to something else for my particular mod setup but I can't find how you're finding your number value to change it to something else.

It's not the standard JavaScript number and it's not ASCII. What standard are you using so I can look up a table?

**Comment by qudix** [comment]
I had added a link to the reference in the config file in 0.2.4

https://creationkit.com/index.php?title=Input_Script#DXScanCodes
