### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Iruil999** [Qudix/QUI-SKSE#27]
Hello. Not full localization in QUI. In QUI_RUSSIAN.txt everything is translated. But not all titles are translated in the game. [Screenshot](https://drive.google.com/file/d/1dxuTYXQ_z9j77xisZQ9MGVSwKJXniwmf/view?usp=sharing).
QUI v0.2.5/Skyrim v1.6.353.0.

**Comment by qudix** [comment]
This is a tough nut to crack. I don't have access to other language variants of the game so I can't test to see what's wrong.

**Comment by qudix** [comment]
I figured it out, should be fixed in the next release.

**Comment by qudix** [comment]
This should now be fixed in the v0.3.0 release.
