### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by orangej20** [Qudix/QUI-SKSE#28]
I am having issues installing this with mod loaders, and before I manually install it I am just wondering what the exact manual installation procedure would look like. I would love to use this mod but I also don't want to put things that I don't need to install into my Skyrim directory.

Thank you!

**Comment by qudix** [comment]
If you can't install it with a mod manager, I kind of doubt manually installing it will change much. It's no different to other mods that go in the data folder.

**Comment by SquidHM3** [comment]
I didn't want to open a new issue, and mine is similar to this one. I've installed the mod via vortex (just used "install from file"), and have the dependencies installed, but nothing shows up at all in game when I hit F11. I am curious - do we have to have the "Header File for DLL Plugin Author" that's listed as the first optional file? I have no idea how to use this mod.

**Comment by Faen668** [comment]
@SquidHM3 Are you sure you installed the correct version? I have read plenty of comments on Nexus from people saying the same thing who simply installed the SE version instead of AE etc.

**Comment by Faen668** [comment]
@Orangej20 just download the zip and drag it into vortex or mo2 and click install, literally that simple. You don’t have to do it manually or mess with your data folder.

**Comment by SquidHM3** [comment]
> @SquidHM3 Are you sure you installed the correct version? I have read plenty of comments on Nexus from people saying the same thing who simply installed the SE version instead of AE etc.

I'll check that to be safe - I am reasonably sure I did download the AE version, but it never hurts to do a double-take to be safe. :) I'll let you know in the paragraph down below after "EDIT:"

EDIT: Nope, I downloaded "All in one (Anniversary Edition)" of Address Library (I'm assuming that is the mod you're referring to?"

**Comment by qudix** [comment]
You have to pick the right mod file too.
QUI-*SE* for Special Edition
QUI-*AE* for Anniversary Edition

**Comment by SquidHM3** [comment]
Ok, that's helpful Qudix. I downloaded the file as a zip archive. I DO see "bootstrap*-AE and bootstrap*-SE" under the /etc directory, but when I installed it using Vortex, there was no way I saw to tell it "use the AE version". I'm sure I sound like an idiot, but at this point I have no idea what to do or how to proceed. It sounds like a lot more than just dragging the zip file into your mod manager and going for it. Did I download the file improperly?  On the "Code" tab, I went to the green Code button, clicked it, and downloaded the "zip" file (the 3rd and last option). Is that where I made my error?

Thanks for your patience. I can build/repair computers blindfolded, but programming? Well, let's just say the perfect meme for my programming skills is the Picard facepalm. :)

EDIT: Perhaps I need to extract it and run the batch files? I won't do that until hearing from you though. I don't want to muck anything up!

EDIT 2: I re-read what I posted in paragraph one. Let me clarify. I downloaded the entire archive as a zip using the procedure above, and then I imported that whole zip file into Vortex. I did _not_ extract the archive when I imported it into Vortex. I only extracted the archive into a separate directory to examine its contents. Hope that helps?

**Comment by qudix** [comment]
Uh... *what*. Why are you downloading the repo? You need to download from the releases section
https://github.com/Qudix/QUI-SKSE/releases

**Comment by SquidHM3** [comment]
That's what I needed. It appears to be working fine now. I did download the file wrong initially. That's surely a setup to fail. :) 
I'll bookmark that page above. There doesn't seem to be an easy way to get to it by going through the menus [Code, Issues, Pull Requests, etc]. That way I'll be able to head right to the release page. Thank you sir. Issue solved. :)

**Comment by qudix** [comment]
![image](https://user-images.githubusercontent.com/17361645/157990268-6219a2fb-eea5-427f-bb7d-b033aab10cee.png)

**Comment by qudix** [comment]
As orangej20 hasn't posted a response so far, I'm closing this issue. Feel free to re-open if the problem hasn't been resolved.
