### ISSUE TITLE
Small Skyrim update after AE update cause qui to stop working?

### ISSUE THREAD

**Issue by werdup1** [Qudix/QUI-SKSE#3]
It seems that a small Skyrim update that happened after the AE update caused this mod to not work anymore for me. Press F11 and no menu. Anyone else? Thanks!

**Comment by qudix** [comment]
I now have separate builds for SE and AE in the releases section. Let me know it doesn't work.

**Comment by Stas-sudo** [comment]
Can confirm that AE build 0.2.1 doesn't work. SKSE says it's incompatible with current runtime version.
![skse](https://user-images.githubusercontent.com/69576219/144743277-1f6e96e8-d44c-484d-b5d5-9c24d533d5c9.png)

**Comment by qudix** [comment]
What game version are you on?

**Comment by Stas-sudo** [comment]
Version 1.6.323. 
SKSE v. 2.1.3

**Comment by qudix** [comment]
And do you have Address Library installed?

**Comment by Stas-sudo** [comment]
Yes, I do. The latest version of it for 1.6.323 version of the game.

**Comment by qudix** [comment]
I'm not sure then. I downloaded the release and tried it on my machine and it works fine.

**Comment by qudix** [comment]
[File Redacted]
Just to be sure it's not a github cache issue, I re-uploaded it here.

**Comment by Stas-sudo** [comment]
All of the guys I've recommended your mod have the same problem as me unfortunately. 


I will try the the link you provided in 5 minutes and let you know

**Comment by Stas-sudo** [comment]
So i've tried the zip you attached. Now SKSE Plugin loader doesn't say it's incompatible , but when i loaded my save the 1st time i've got CTD , second time i managed to load the game but as soon as i used F11 button i've got CTD too.

**Comment by qudix** [comment]
I'm not sure what that could be, but as NET Framework hasn't been updated for AE yet, I can't take a closer look without a crash log.

**Comment by Stas-sudo** [comment]
Could you tell me please , where i can get the crash log ?

**Comment by qudix** [comment]
You can't because like I said NET Framework hasn't been updated yet

**Comment by Stas-sudo** [comment]
Sorry my bad. Well , i will be patiently waiting for a next builds. Maybe the problem will be solved in future.

Thank you for your mod and time spent on me here :)

Cheers!

**Comment by werdup1** [comment]
> [QUI-AE-0.2.1.zip](https://github.com/Qudix/QUI-SKSE/files/7656647/QUI-AE-0.2.1.zip) Just to be sure it's not a github cache issue, I re-uploaded it here.

This one is working for me. Thanks!

**Comment by Osmosis-Wrench** [comment]
> Sorry my bad. Well , i will be patiently waiting for a next builds. Maybe the problem will be solved in future.
> 
> Thank you for your mod and time spent on me here :)
> 
> Cheers!

https://www.nexusmods.com/skyrimspecialedition/mods/59596
Could you try installing this and then posting the crash log? It'll be in "Documents\My Games\Skyrim Special Edition\SKSE"

**Comment by Stas-sudo** [comment]
@Osmosis-Wrench here's the crash log.
[crash-2021-12-06-09-43-32.log](https://github.com/Qudix/QUI-SKSE/files/7659699/crash-2021-12-06-09-43-32.log)

**Comment by qudix** [comment]
I want to try something. Do you already have an `<Wherever you have the game installed>/Data/SKSE/SKSE.ini` file? If not, extract and copy [this](https://github.com/Qudix/QUI-SKSE/files/7663350/SKSE.zip) ini file in that path.

 Then re-create the crash. If all went well there should be a minidump in `Documents/My Games/Skyrim Special Edition/SKSE/Minidumps/`. If so copy that and paste it here. If it's too big, then we'll have to figure out another transfer method.

**Comment by Stas-sudo** [comment]
During the tries to crash i've managed to launch the mod one time at least :)

![ScreenShot45](https://user-images.githubusercontent.com/69576219/144925518-0d46d3d0-6e5a-4c89-8d73-6ed07eaf4c73.png)

The crash dumps ( added a couple of dumps of a crash just in case if you need it)
[2021-12-06_21.34.09.zip](https://github.com/Qudix/QUI-SKSE/files/7663668/2021-12-06_21.34.09.zip)
[2021-12-06_21.40.20.zip](https://github.com/Qudix/QUI-SKSE/files/7663707/2021-12-06_21.40.20.zip)
[2021-12-06_21.52.11.zip](https://github.com/Qudix/QUI-SKSE/files/7663775/2021-12-06_21.52.11.zip)

Also i've checked the QUi log in the documents folder.
The end of the log has some kind of problem to open the config of other mod.
![QUI](https://user-images.githubusercontent.com/69576219/144930605-cc002c63-9e3c-4e01-acdd-534c4f0f3b8d.png)

**Comment by qudix** [comment]
Don't worry about that log, it's just printing whatever pops up in scaleform land.

Also, that dmp really helps. I found the problem.

**Comment by Stas-sudo** [comment]
@Qudix Awesome, glad to help you 👍

**Comment by qudix** [comment]
[File Redacted]
Alright, not sure if this will fix it, but worth a try.

**Comment by Stas-sudo** [comment]
@Qudix First time i loaded my recent save it worked. Decided to load the other save from yesterday to check the mod there and got CTD as soon as i used F11

Restarded the game and loaded the same recent save where i've got the mod working last time ,  used F11 also got CTD. 
Attaching the last 2 crashes.
[2021-12-06_22.58.16.zip](https://github.com/Qudix/QUI-SKSE/files/7664103/2021-12-06_22.58.16.zip)
[2021-12-06_23.02.28.zip](https://github.com/Qudix/QUI-SKSE/files/7664102/2021-12-06_23.02.28.zip)

**Comment by qudix** [comment]
[QUI-AE-0.2.2-test2.zip](https://github.com/Qudix/QUI-SKSE/files/7665094/QUI-AE-0.2.2-test2.zip)
I worked on this one for a while longer. Time for test 2.

**Comment by Xealdor** [comment]
Created an account to say that I too have been having the issue in this thread, and your 0.2.2test build fixed the f11 CTD for me. Thank you for your work.

**Comment by Stas-sudo** [comment]
> [QUI-AE-0.2.2-test2.zip](https://github.com/Qudix/QUI-SKSE/files/7665094/QUI-AE-0.2.2-test2.zip) I worked on this one for a while longer. Time for test 2.

Can confirm . No CTD with test 2 version. Even on the save where i've got CTD's every time. 

Good job mate! 🥇

**Comment by qudix** [comment]
I'll be officially releasing a new version later today.
