### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by xerokin** [Qudix/QUI-SKSE#31]
i cannot get this to work no matter what i do :( i downloaded the most recent release (0.2.8) through NMM, but hitting F11 in-game doesn't pull up anything. not sure what i'm doing wrong (i have all dependencies as well)

**Comment by qudix** [comment]
You didn't specify what version of the game you have and the version (AE or SE) of this mod you downloaded.

**Comment by xerokin** [comment]
oh, sorry!! i have skyrim se version 1.6.353.0 and i'm using the se version of this mod

**Comment by qudix** [comment]
1.6.353 is AE, you need the AE version.

**Comment by xerokin** [comment]
ah, that was the issue... i installed the ae ver. and it worked perfectly. i had no idea since i never upgraded to anniversary and have always used se mods without problem until now. sorry for the dumb question, and thank you!

**Comment by qudix** [comment]
When we say AE, we are referring to the AE *update* which is free.
