### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by Iruil999** [Qudix/QUI-SKSE#33]
Can you replace the Russian localization? I think my translation is better.
[QUI_RUSSIAN.txt](https://github.com/Qudix/QUI-SKSE/files/9018128/QUI_RUSSIAN.txt)

And a small question. What is the "Note" category? I haven't seen this category in any esp/esm.

**Comment by qudix** [comment]
I completely missed this issue, sorry. I'll try and get the updated translation in the next release.

The Note category just corresponds to the NOTE form type, you can see them in xedit.

**Comment by Iruil999** [comment]
Ok. If you will use my translation, take this one 
[QUI_RUSSIAN.txt](https://github.com/Qudix/QUI-SKSE/files/9692715/QUI_RUSSIAN.txt)

**Comment by qudix** [comment]
Should be included in the next update
