### ISSUE TITLE
Update broke the mod

### ISSUE THREAD

**Issue by christiandlloyd** [Qudix/QUI-SKSE#35]
Idk if you still work on this or know about it, but SAE got updated and skse won't load the dll

**Comment by qudix** [comment]
Could you test this build and tell me if it works? Theoretically it should work for both SE and AE.

[QUI-TestBuild.zip](https://github.com/Qudix/QUI-SKSE/files/9689563/QUI-TestBuild.zip)

**Comment by christiandlloyd** [comment]
Yeah this version works now, skse no longer gets angry. Thanks boss!
