### ISSUE TITLE
Won't load QUI.dll

### ISSUE THREAD

**Issue by christiandlloyd** [Qudix/QUI-SKSE#4]
Just installed newest AE version of QUI, and I get this message when I try to load it:
"A DLL plugin has failed to load correctly. If a new version of Skyrim was just released, it probably needs to be updated. Please contact the plugin's author for more information.

 QUI.dll: disabled, incompatible with current runtime version.

Continuing to load may result in lost save data or other undesired behavior.
Exit game? (yes highly suggested)"

Any update coming soon?

**Comment by qudix** [comment]
I uploaded a new build for AE in the releases section, please test it and let me know if it doesn't work.
