### ISSUE TITLE
CTD while pressing F11

### ISSUE THREAD

**Issue by glasslemons** [Qudix/QUI-SKSE#5]
Similar to another issue here, my game freezes up and crashes seemingly every time I press f11. It most likely is an issue on my end, but i'm not exactly knowledgeable in the understanding the logs. I'll attach the crash log to get any feedback
[Crash_2021_12_4_7-2-14.txt](https://github.com/Qudix/QUI-SKSE/files/7654153/Crash_2021_12_4_7-2-14.txt)

**Comment by christiandlloyd** [comment]
If you're on AE, download the newest version for AE. It has since been patched.

**Comment by glasslemons** [comment]
I'm not on AE, i am using the best of both worlds patcher for unofficial skyrim downgrader

**Comment by qudix** [comment]
This should be fixed in the next official release coming later today.

**Comment by qudix** [comment]
This is now fixed in the latest 0.2.2 release.

**Comment by sibouazza13** [comment]
F11 didn't work at all i need help plz
