### ISSUE TITLE
QUI-AE-0.2.2-test2 Build Does Not Have Ingredients  In Any Searchable Containers

### ISSUE THREAD

**Issue by Xealdor** [Qudix/QUI-SKSE#7]
Current Test build does not seem to show any items in any plugin container with ingredients only, or any ingredients in plugins that contain them. 
For example; the Skyrim Master, will not show any alchemy ingredients, but all other types show.
If the player has any mod or plugin that ONLY contains ingredients they will not show up in the pop up window.

**Comment by qudix** [comment]
I actually just forgot to include those; I'll add it for the next release.

**Comment by qudix** [comment]
![ScreenShot5](https://user-images.githubusercontent.com/17361645/145090461-bef1d2fb-9039-4fee-84d4-4c2eee2b91d0.png)

**Comment by qudix** [comment]
This is now fixed in the latest 0.2.2 release.
