### ISSUE TITLE
SKSE ver.

### ISSUE THREAD

**Issue by plankton11** [Qudix/QUI-SKSE#9]
Which version of SKSE is this plugin for?

**Comment by qudix** [comment]
They both require Address Library
pre-AE: 1.5.39 up to 1.5.97
post-AE: 1.6.317 up to 1.6.323

**Comment by Wieber01** [comment]
Hey so which address library do you mean? The skse plugin on the nexus or the fallout 4 one you linked? 🤔 Might be a stupid question but i tries both of them and nothing happens when i push f11 🤔

**Comment by qudix** [comment]
Oops, wrong link. Also, you need to provide more info other than "nothing happens", like is there a log in `My Documents/My Games/Skyrim Special Edition/SKSE/QUI.log`? Does SKSE spit out an error? Are you using the right build for the right version of the game?

**Comment by YummyFrogits** [comment]
Personally for me nothing loads when i press f11, and theres a log in my skse folder but it just doesnt seem to be loading. I'm using post AE edition

**Comment by Wieber01** [comment]
> Oops, wrong link. Also, you need to provide more info other than "nothing happens", like is there a log in `My Documents/My Games/Skyrim Special Edition/SKSE/QUI.log`? Does SKSE spit out an error? Are you using the right build for the right version of the game?

So sorry for the late answer. But yes i am using the right version ( the AE Version), but no QUI.log unfortunately. Like i said nothing happens when i press f11 no error or menu. I tried installing your mod via MO2 and manually but no luck. 

The address library plugin i am using is the ae version as well by the way so i don't know what i am doing wrong. Any ideas?

**Comment by dfmarulanda** [comment]
Same issue here, but playing on SSE

**Comment by qudix** [comment]
As the mod works for most people I'll just have to assume it's on your end. If you still can't get it to work please open an issue with more detail than "it no work, pls fix`
